// Mock library generated by Copilot

function assert(condition, message) {
  return {
    strictEqual: function (actual, expected, message) {
      if (actual !== expected) {
        throw new Error(
          message || `Expected ${expected} but received ${actual}`
        );
      }
    },
    deepStrictEqual: function (actual, expected, message) {
      if (JSON.stringify(actual) !== JSON.stringify(expected)) {
        throw new Error(
          message ||
            `Expected ${JSON.stringify(expected)} but received ${JSON.stringify(
              actual
            )}`
        );
      }
    },
  };
}

module.exports = { assert };
